# Form implementation generated from reading ui file 'add_entry.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(312, 244)
        self.sugarLevelInput = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.sugarLevelInput.setGeometry(QtCore.QRect(40, 20, 231, 41))
        self.sugarLevelInput.setObjectName("sugarLevelInput")
        self.dateInput = QtWidgets.QDateEdit(parent=Dialog)
        self.dateInput.setGeometry(QtCore.QRect(40, 60, 141, 41))
        self.dateInput.setObjectName("dateInput")
        self.timeInput = QtWidgets.QTimeEdit(parent=Dialog)
        self.timeInput.setGeometry(QtCore.QRect(180, 60, 91, 41))
        self.timeInput.setObjectName("timeInput")
        self.addButton = QtWidgets.QPushButton(parent=Dialog)
        self.addButton.setGeometry(QtCore.QRect(100, 130, 111, 71))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addButton.setText(_translate("Dialog", "DODAJ"))
