# Form implementation generated from reading ui file 'add_entry.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_entry(object):
    def setupUi(self, add_entry):
        add_entry.setObjectName("add_entry")
        add_entry.resize(312, 244)
        self.sugarLevelInput = QtWidgets.QDoubleSpinBox(parent=add_entry)
        self.sugarLevelInput.setGeometry(QtCore.QRect(40, 20, 231, 41))
        self.sugarLevelInput.setDecimals(1)
        self.sugarLevelInput.setMinimum(25.0)
        self.sugarLevelInput.setMaximum(500.0)
        self.sugarLevelInput.setProperty("value", 80.0)
        self.sugarLevelInput.setObjectName("sugarLevelInput")
        self.dateInput = QtWidgets.QDateEdit(parent=add_entry)
        self.dateInput.setGeometry(QtCore.QRect(40, 60, 141, 41))
        self.dateInput.setObjectName("dateInput")
        self.timeInput = QtWidgets.QTimeEdit(parent=add_entry)
        self.timeInput.setGeometry(QtCore.QRect(180, 60, 91, 41))
        self.timeInput.setObjectName("timeInput")
        self.addButton = QtWidgets.QPushButton(parent=add_entry)
        self.addButton.setGeometry(QtCore.QRect(100, 130, 111, 71))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(add_entry)
        QtCore.QMetaObject.connectSlotsByName(add_entry)

    def retranslateUi(self, add_entry):
        _translate = QtCore.QCoreApplication.translate
        add_entry.setWindowTitle(_translate("add_entry", "Dodaj wpis"))
        self.addButton.setText(_translate("add_entry", "DODAJ"))
