# Form implementation generated from reading ui file 'footer.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_footer(object):
    def setupUi(self, footer):
        footer.setObjectName("footer")
        footer.resize(684, 62)
        footer.setMinimumSize(QtCore.QSize(0, 0))
        footer.setMaximumSize(QtCore.QSize(16777215, 80))
        self.horizontalLayout = QtWidgets.QHBoxLayout(footer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.export_button = QtWidgets.QPushButton(parent=footer)
        self.export_button.setMinimumSize(QtCore.QSize(0, 50))
        self.export_button.setObjectName("export_button")
        self.horizontalLayout.addWidget(self.export_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.import_button = QtWidgets.QPushButton(parent=footer)
        self.import_button.setMinimumSize(QtCore.QSize(0, 50))
        self.import_button.setObjectName("import_button")
        self.horizontalLayout.addWidget(self.import_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.add_entry_button = QtWidgets.QPushButton(parent=footer)
        self.add_entry_button.setMinimumSize(QtCore.QSize(0, 50))
        self.add_entry_button.setObjectName("add_entry_button")
        self.horizontalLayout.addWidget(self.add_entry_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(footer)
        QtCore.QMetaObject.connectSlotsByName(footer)

    def retranslateUi(self, footer):
        _translate = QtCore.QCoreApplication.translate
        footer.setWindowTitle(_translate("footer", "Form"))
        self.export_button.setText(_translate("footer", "Exportuj"))
        self.import_button.setText(_translate("footer", "Importuj"))
        self.add_entry_button.setText(_translate("footer", "Dodaj wpis"))
