# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_graph(object):
    def setupUi(self, graph):
        graph.setObjectName("graph")
        graph.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(graph)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_widget = PlotWidget(parent=graph)
        self.graph_widget.setObjectName("graph_widget")
        self.verticalLayout.addWidget(self.graph_widget)
        self.date_frame = QtWidgets.QFrame(parent=graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_frame.sizePolicy().hasHeightForWidth())
        self.date_frame.setSizePolicy(sizePolicy)
        self.date_frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.date_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.date_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.date_frame.setObjectName("date_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.date_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.from_label = QtWidgets.QLabel(parent=self.date_frame)
        self.from_label.setMaximumSize(QtCore.QSize(15, 16777215))
        self.from_label.setObjectName("from_label")
        self.horizontalLayout.addWidget(self.from_label)
        self.from_dateEdit = QtWidgets.QDateEdit(parent=self.date_frame)
        self.from_dateEdit.setMinimumSize(QtCore.QSize(80, 40))
        self.from_dateEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.from_dateEdit.setObjectName("from_dateEdit")
        self.horizontalLayout.addWidget(self.from_dateEdit)
        self.to_label = QtWidgets.QLabel(parent=self.date_frame)
        self.to_label.setMaximumSize(QtCore.QSize(15, 16777215))
        self.to_label.setObjectName("to_label")
        self.horizontalLayout.addWidget(self.to_label)
        self.to_dateEdit = QtWidgets.QDateEdit(parent=self.date_frame)
        self.to_dateEdit.setMinimumSize(QtCore.QSize(80, 40))
        self.to_dateEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.to_dateEdit.setObjectName("to_dateEdit")
        self.horizontalLayout.addWidget(self.to_dateEdit)
        self.date_reset_button = QtWidgets.QPushButton(parent=self.date_frame)
        self.date_reset_button.setMinimumSize(QtCore.QSize(0, 50))
        self.date_reset_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.date_reset_button.setObjectName("date_reset_button")
        self.horizontalLayout.addWidget(self.date_reset_button, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addWidget(self.date_frame)

        self.retranslateUi(graph)
        QtCore.QMetaObject.connectSlotsByName(graph)

    def retranslateUi(self, graph):
        _translate = QtCore.QCoreApplication.translate
        graph.setWindowTitle(_translate("graph", "Form"))
        self.from_label.setText(_translate("graph", "Od"))
        self.to_label.setText(_translate("graph", "Do"))
        self.date_reset_button.setText(_translate("graph", "Cały zakres"))
from pyqtgraph import PlotWidget
