# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_graph(object):
    def setupUi(self, graph):
        graph.setObjectName("graph")
        graph.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=graph)
        self.label.setGeometry(QtCore.QRect(190, 120, 81, 21))
        self.label.setObjectName("label")

        self.retranslateUi(graph)
        QtCore.QMetaObject.connectSlotsByName(graph)

    def retranslateUi(self, graph):
        _translate = QtCore.QCoreApplication.translate
        graph.setWindowTitle(_translate("graph", "Form"))
        self.label.setText(_translate("graph", "Wykres"))
