# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_graph(object):
    def setupUi(self, graph):
        graph.setObjectName("graph")
        graph.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(graph)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_widget = PlotWidget(parent=graph)
        self.graph_widget.setObjectName("graph_widget")
        self.verticalLayout.addWidget(self.graph_widget)
        self.date_frame = QtWidgets.QFrame(parent=graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_frame.sizePolicy().hasHeightForWidth())
        self.date_frame.setSizePolicy(sizePolicy)
        self.date_frame.setMaximumSize(QtCore.QSize(200, 120))
        self.date_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.date_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.date_frame.setObjectName("date_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.date_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.date_layout = QtWidgets.QGridLayout()
        self.date_layout.setHorizontalSpacing(5)
        self.date_layout.setVerticalSpacing(2)
        self.date_layout.setObjectName("date_layout")
        self.to_label = QtWidgets.QLabel(parent=self.date_frame)
        self.to_label.setMaximumSize(QtCore.QSize(15, 16777215))
        self.to_label.setObjectName("to_label")
        self.date_layout.addWidget(self.to_label, 1, 0, 1, 1)
        self.from_label = QtWidgets.QLabel(parent=self.date_frame)
        self.from_label.setMaximumSize(QtCore.QSize(15, 16777215))
        self.from_label.setObjectName("from_label")
        self.date_layout.addWidget(self.from_label, 0, 0, 1, 1)
        self.from_dateEdit = QtWidgets.QDateEdit(parent=self.date_frame)
        self.from_dateEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.from_dateEdit.setObjectName("from_dateEdit")
        self.date_layout.addWidget(self.from_dateEdit, 0, 1, 1, 1)
        self.to_dateEdit = QtWidgets.QDateEdit(parent=self.date_frame)
        self.to_dateEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.to_dateEdit.setObjectName("to_dateEdit")
        self.date_layout.addWidget(self.to_dateEdit, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.date_layout)
        self.verticalLayout.addWidget(self.date_frame)

        self.retranslateUi(graph)
        QtCore.QMetaObject.connectSlotsByName(graph)

    def retranslateUi(self, graph):
        _translate = QtCore.QCoreApplication.translate
        graph.setWindowTitle(_translate("graph", "Form"))
        self.to_label.setText(_translate("graph", "Do"))
        self.from_label.setText(_translate("graph", "Od"))
from pyqtgraph import PlotWidget
