# Form implementation generated from reading ui file 'header.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_haeder(object):
    def setupUi(self, haeder):
        haeder.setObjectName("haeder")
        haeder.resize(503, 76)
        self.label = QtWidgets.QLabel(parent=haeder)
        self.label.setGeometry(QtCore.QRect(190, 10, 181, 41))
        self.label.setObjectName("label")

        self.retranslateUi(haeder)
        QtCore.QMetaObject.connectSlotsByName(haeder)

    def retranslateUi(self, haeder):
        _translate = QtCore.QCoreApplication.translate
        haeder.setWindowTitle(_translate("haeder", "Form"))
        self.label.setText(_translate("haeder", " DZIENNIK SKIBIDIDIABETYKA"))
