# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(545, 483)
        self.centralwidget = QtWidgets.QWidget(parent=main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.header_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.header_layout = QtWidgets.QHBoxLayout()
        self.header_layout.setObjectName("header_layout")
        self.horizontalLayout_2.addLayout(self.header_layout)
        self.verticalLayout.addWidget(self.header_frame)
        self.content_layout = QtWidgets.QHBoxLayout()
        self.content_layout.setObjectName("content_layout")
        self.search_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.search_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.search_frame.setObjectName("search_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.search_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setObjectName("search_layout")
        self.horizontalLayout_3.addLayout(self.search_layout)
        self.content_layout.addWidget(self.search_frame)
        self.graph_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.graph_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.graph_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.graph_frame.setObjectName("graph_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.graph_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graph_layout = QtWidgets.QHBoxLayout()
        self.graph_layout.setObjectName("graph_layout")
        self.horizontalLayout_6.addLayout(self.graph_layout)
        self.content_layout.addWidget(self.graph_frame)
        self.verticalLayout.addLayout(self.content_layout)
        self.add_entry_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_entry_button.setObjectName("add_entry_button")
        self.verticalLayout.addWidget(self.add_entry_button, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 545, 18))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Dziennik diabetyka"))
        self.add_entry_button.setText(_translate("main_window", "Dodaj wpis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec())
