# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(parent=main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_layout = QtWidgets.QHBoxLayout()
        self.content_layout.setObjectName("content_layout")
        self.search_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.search_frame.setMinimumSize(QtCore.QSize(250, 0))
        self.search_frame.setMaximumSize(QtCore.QSize(450, 16777215))
        self.search_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.search_frame.setObjectName("search_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.search_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_layout = QtWidgets.QVBoxLayout()
        self.search_layout.setObjectName("search_layout")
        self.horizontalLayout_3.addLayout(self.search_layout)
        self.content_layout.addWidget(self.search_frame)
        self.graph_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.graph_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.graph_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.graph_frame.setObjectName("graph_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.graph_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graph_layout = QtWidgets.QHBoxLayout()
        self.graph_layout.setObjectName("graph_layout")
        self.horizontalLayout_6.addLayout(self.graph_layout)
        self.content_layout.addWidget(self.graph_frame)
        self.verticalLayout.addLayout(self.content_layout)
        self.footer_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.footer_frame.setEnabled(True)
        self.footer_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.footer_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.footer_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.footer_layout = QtWidgets.QHBoxLayout()
        self.footer_layout.setObjectName("footer_layout")
        self.horizontalLayout_2.addLayout(self.footer_layout)
        self.verticalLayout.addWidget(self.footer_frame)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 18))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Dziennik diabetyka"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec())
