# Form implementation generated from reading ui file 'measurements_list.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_measurements_list(object):
    def setupUi(self, measurements_list):
        measurements_list.setObjectName("measurements_list")
        measurements_list.resize(684, 520)
        self.verticalLayout = QtWidgets.QVBoxLayout(measurements_list)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=measurements_list)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.table = QtWidgets.QTableWidget(parent=measurements_list)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.table.setStyleSheet("QTableWidget::item {\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3a3a3a;\n"
"}\n"
"\n"
"QPushButton {\n"
"    min-width: 30px;\n"
"    max-width: 30px;\n"
"    min-height: 24px;\n"
"    max-height: 24px;\n"
"    padding: 0px;\n"
"}")
        self.table.setObjectName("table")
        self.table.setColumnCount(4)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.table)

        self.retranslateUi(measurements_list)
        QtCore.QMetaObject.connectSlotsByName(measurements_list)

    def retranslateUi(self, measurements_list):
        _translate = QtCore.QCoreApplication.translate
        measurements_list.setWindowTitle(_translate("measurements_list", "Form"))
        self.title_label.setText(_translate("measurements_list", "Lista pomiarów"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("measurements_list", "Data"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("measurements_list", "Godzina"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("measurements_list", "Poziom cukru"))
