# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_search(object):
    def setupUi(self, search):
        search.setObjectName("search")
        search.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=search)
        self.label.setGeometry(QtCore.QRect(150, 120, 81, 21))
        self.label.setObjectName("label")

        self.retranslateUi(search)
        QtCore.QMetaObject.connectSlotsByName(search)

    def retranslateUi(self, search):
        _translate = QtCore.QCoreApplication.translate
        search.setWindowTitle(_translate("search", "Form"))
        self.label.setText(_translate("search", "Wyszukiwanie"))
